// <auto-generated />
using System;
using Certeo.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Certeo.Api.Infrastructure.Migrations
{
    [DbContext(typeof(CerteoDbContext))]
    partial class CerteoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Certeo.Api.Modules.Applications.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ApplicationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("CoverLetter")
                        .HasColumnType("text");

                    b.Property<string>("CurrentOccupation")
                        .HasColumnType("text");

                    b.Property<string>("CvUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<Guid?>("EducationLevelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("GenderId")
                        .HasColumnType("uuid");

                    b.Property<int?>("GraduationYear")
                        .HasColumnType("integer");

                    b.Property<bool?>("HasPersonalComputer")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OdcDiscoverySourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PortfolioUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ScheduledPurgeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SchoolOrUniversity")
                        .HasColumnType("text");

                    b.Property<string>("Specialization")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TrainingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EducationLevelId");

                    b.HasIndex("FileNumber")
                        .IsUnique();

                    b.HasIndex("GenderId");

                    b.HasIndex("OdcDiscoverySourceId");

                    b.HasIndex("TrainingId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Applications.ApplicationAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TrainingQuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("TrainingQuestionId");

                    b.ToTable("ApplicationAnswers");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Certificates.Certificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EvaluationAttemptId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSharedOnLinkedIn")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<string>("PdfUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TrainingId")
                        .HasColumnType("uuid");

                    b.Property<string>("VerificationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationAttemptId");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("TrainingId");

                    b.HasIndex("VerificationCode")
                        .IsUnique();

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Evaluations.AttemptAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("EarnedPoints")
                        .HasColumnType("integer");

                    b.Property<Guid>("EvaluationAttemptId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EvaluationQuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SelectedOptionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationAttemptId");

                    b.HasIndex("EvaluationQuestionId");

                    b.HasIndex("SelectedOptionId");

                    b.ToTable("AttemptAnswers");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Evaluations.Evaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("EstimatedDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("MaxAllowedAttempts")
                        .HasColumnType("integer");

                    b.Property<int>("PassingScorePercentage")
                        .HasColumnType("integer");

                    b.Property<bool>("ShouldShuffleOptions")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShouldShuffleQuestions")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TrainingId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TrainingId")
                        .IsUnique();

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Evaluations.EvaluationAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("EarnedScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("EvaluationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasPassed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("EvaluationAttempts");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Evaluations.EvaluationQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EvaluationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId");

                    b.ToTable("EvaluationQuestions");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Evaluations.QuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EvaluationQuestionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationQuestionId");

                    b.ToTable("QuestionOptions");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Identity.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("text");

                    b.Property<string>("Entity")
                        .HasColumnType("text");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PerformedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Name")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Certeo.Api.Modules.MasterData.ReferenceData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Code")
                        .IsUnique();

                    b.ToTable("ReferenceData");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Participants.Attendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgeRangeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DistanceFromCenterMeters")
                        .HasColumnType("numeric");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TrainingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VisitReasonId")
                        .HasColumnType("uuid");

                    b.Property<string>("VisitorEmail")
                        .HasColumnType("text");

                    b.Property<string>("VisitorFirstName")
                        .HasColumnType("text");

                    b.Property<string>("VisitorLastName")
                        .HasColumnType("text");

                    b.Property<string>("VisitorPhone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgeRangeId");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("TrainingId");

                    b.HasIndex("VisitReasonId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Participants.AttendanceProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttendanceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceId");

                    b.HasIndex("ProfileId");

                    b.ToTable("AttendanceProfiles");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Participants.CenterQrCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("CenterQrCodes");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Participants.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AttendanceRate")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Settings.EmailTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("EmailTemplates");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Settings.SystemSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedLinkedInApiKey")
                        .HasColumnType("text");

                    b.Property<string>("EncryptedSmtpPassword")
                        .HasColumnType("text");

                    b.Property<bool>("IsLinkedInSharingAllowed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNewApplicationAlertEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOdcSyncActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPasswordSpecialCharRequired")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPasswordUppercaseRequired")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemUpdateAlertEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTrainingReminderAlertEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<int>("MinPasswordLength")
                        .HasColumnType("integer");

                    b.Property<int?>("PasswordExpirationDays")
                        .HasColumnType("integer");

                    b.Property<int>("SessionTimeoutMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("SmtpHost")
                        .HasColumnType("text");

                    b.Property<int?>("SmtpPort")
                        .HasColumnType("integer");

                    b.Property<string>("SmtpUsername")
                        .HasColumnType("text");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Trainings.Training", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ApplicationDeadline")
                        .HasColumnType("date");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsCertificateEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsQuizMandatory")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("integer");

                    b.Property<int>("MinCapacity")
                        .HasColumnType("integer");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("PromotionalPosterUrl")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SocialMediaMessage")
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TargetAudience")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Trainings.TrainingApplicationField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Field")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TrainingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrainingId", "Field")
                        .IsUnique();

                    b.ToTable("TrainingApplicationFields");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Trainings.TrainingQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TrainingId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TrainingId");

                    b.ToTable("TrainingQuestions");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Applications.Application", b =>
                {
                    b.HasOne("Certeo.Api.Modules.MasterData.ReferenceData", "EducationLevel")
                        .WithMany()
                        .HasForeignKey("EducationLevelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Certeo.Api.Modules.MasterData.ReferenceData", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Certeo.Api.Modules.MasterData.ReferenceData", "OdcDiscoverySource")
                        .WithMany()
                        .HasForeignKey("OdcDiscoverySourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Certeo.Api.Modules.Trainings.Training", "Training")
                        .WithMany("Applications")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EducationLevel");

                    b.Navigation("Gender");

                    b.Navigation("OdcDiscoverySource");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Applications.ApplicationAnswer", b =>
                {
                    b.HasOne("Certeo.Api.Modules.Applications.Application", "Application")
                        .WithMany("Answers")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Certeo.Api.Modules.Trainings.TrainingQuestion", "TrainingQuestion")
                        .WithMany()
                        .HasForeignKey("TrainingQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("TrainingQuestion");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Certificates.Certificate", b =>
                {
                    b.HasOne("Certeo.Api.Modules.Evaluations.EvaluationAttempt", "EvaluationAttempt")
                        .WithMany()
                        .HasForeignKey("EvaluationAttemptId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Certeo.Api.Modules.Participants.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Certeo.Api.Modules.Trainings.Training", "Training")
                        .WithMany()
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EvaluationAttempt");

                    b.Navigation("Participant");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Evaluations.AttemptAnswer", b =>
                {
                    b.HasOne("Certeo.Api.Modules.Evaluations.EvaluationAttempt", "EvaluationAttempt")
                        .WithMany("Answers")
                        .HasForeignKey("EvaluationAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Certeo.Api.Modules.Evaluations.EvaluationQuestion", "EvaluationQuestion")
                        .WithMany()
                        .HasForeignKey("EvaluationQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Certeo.Api.Modules.Evaluations.QuestionOption", "SelectedOption")
                        .WithMany()
                        .HasForeignKey("SelectedOptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EvaluationAttempt");

                    b.Navigation("EvaluationQuestion");

                    b.Navigation("SelectedOption");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Evaluations.Evaluation", b =>
                {
                    b.HasOne("Certeo.Api.Modules.Trainings.Training", "Training")
                        .WithOne("Evaluation")
                        .HasForeignKey("Certeo.Api.Modules.Evaluations.Evaluation", "TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Training");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Evaluations.EvaluationAttempt", b =>
                {
                    b.HasOne("Certeo.Api.Modules.Evaluations.Evaluation", "Evaluation")
                        .WithMany("Attempts")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Certeo.Api.Modules.Participants.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Evaluations.EvaluationQuestion", b =>
                {
                    b.HasOne("Certeo.Api.Modules.Evaluations.Evaluation", "Evaluation")
                        .WithMany("Questions")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Evaluations.QuestionOption", b =>
                {
                    b.HasOne("Certeo.Api.Modules.Evaluations.EvaluationQuestion", "EvaluationQuestion")
                        .WithMany("Options")
                        .HasForeignKey("EvaluationQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvaluationQuestion");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Identity.AuditLog", b =>
                {
                    b.HasOne("Certeo.Api.Modules.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Identity.RefreshToken", b =>
                {
                    b.HasOne("Certeo.Api.Modules.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Identity.User", b =>
                {
                    b.HasOne("Certeo.Api.Modules.Identity.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Participants.Attendance", b =>
                {
                    b.HasOne("Certeo.Api.Modules.MasterData.ReferenceData", "AgeRange")
                        .WithMany()
                        .HasForeignKey("AgeRangeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Certeo.Api.Modules.Participants.Participant", "Participant")
                        .WithMany("Attendances")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Certeo.Api.Modules.Trainings.Training", "Training")
                        .WithMany()
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Certeo.Api.Modules.MasterData.ReferenceData", "VisitReason")
                        .WithMany()
                        .HasForeignKey("VisitReasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgeRange");

                    b.Navigation("Participant");

                    b.Navigation("Training");

                    b.Navigation("VisitReason");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Participants.AttendanceProfile", b =>
                {
                    b.HasOne("Certeo.Api.Modules.Participants.Attendance", "Attendance")
                        .WithMany("Profiles")
                        .HasForeignKey("AttendanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Certeo.Api.Modules.MasterData.ReferenceData", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attendance");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Participants.Participant", b =>
                {
                    b.HasOne("Certeo.Api.Modules.Applications.Application", "Application")
                        .WithOne("Participant")
                        .HasForeignKey("Certeo.Api.Modules.Participants.Participant", "ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Trainings.Training", b =>
                {
                    b.HasOne("Certeo.Api.Modules.MasterData.ReferenceData", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Certeo.Api.Modules.Identity.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Trainings.TrainingApplicationField", b =>
                {
                    b.HasOne("Certeo.Api.Modules.Trainings.Training", "Training")
                        .WithMany("ApplicationFields")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Training");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Trainings.TrainingQuestion", b =>
                {
                    b.HasOne("Certeo.Api.Modules.Trainings.Training", "Training")
                        .WithMany("CustomQuestions")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Training");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Applications.Application", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Evaluations.Evaluation", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Evaluations.EvaluationAttempt", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Evaluations.EvaluationQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Identity.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Participants.Attendance", b =>
                {
                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Participants.Participant", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("Certeo.Api.Modules.Trainings.Training", b =>
                {
                    b.Navigation("ApplicationFields");

                    b.Navigation("Applications");

                    b.Navigation("CustomQuestions");

                    b.Navigation("Evaluation");
                });
#pragma warning restore 612, 618
        }
    }
}
